csp_enigmatic/website/views.py
from flask import Blueprint, render_template, request, session, flash
import numpy as np
import website.sudoku as sd
from website.word_search import WordSearch
import random

views = Blueprint('views', __name__)

@views.route('/')
def home():
    sudoku = sd.Sudoku.sudoku_generator(0.5)
    words = []

    file = open('words/words.txt', 'r')
    for line in file:
        words.append(line.strip())
    file.close()

    for i in range(len(words)):
        words[i] = words[i].upper()

    wordSearch = WordSearch(10)
    random.shuffle(words)

    for word in words:
        wordSearch.add_word(word)
    return render_template(
        "home.html",
        sudoku=sudoku,
        word_search=wordSearch.generate()
    ) 

@views.route('/sudoku', methods=['GET', 'POST'])
def sudoku():
    if 'current_move_number' not in session:
        session['current_move_number'] = 1

    if request.method == 'POST':
        move_action = request.form.get('move_action')
        if move_action == 'previous':
            if session['current_move_number'] > 1:
                session['current_move_number'] -= 1
        elif move_action == 'next':
            if session['current_move_number'] < len(sd.Sudoku.sudoku_log):
                session['current_move_number'] += 1
            print(sd.Sudoku.coordinates_log[session['current_move_number']])
        elif move_action == 'solve':
            session['current_move_number'] = len(sd.Sudoku.sudoku_log)
        elif move_action == 'reset':
            session['current_move_number'] = 1
        elif move_action == 'generate':
            session['current_move_number'] = 1
            grid = sd.Sudoku.sudoku_generator(0.5)
            sd.Sudoku.solve(grid)
            sd.Sudoku.move_number += 1
            sd.Sudoku.sudoku_log[sd.Sudoku.move_number] = np.copy(grid)
    else:
        session['current_move_number'] = 1
        grid = sd.Sudoku.sudoku_generator(0.5)
        sd.Sudoku.solve(grid)
        sd.Sudoku.move_number += 1
        sd.Sudoku.sudoku_log[sd.Sudoku.move_number] = np.copy(grid)

    current_move_number = session['current_move_number']
    grid = sd.Sudoku.sudoku_log[current_move_number]
    return render_template(
        "sudoku.html",
        current_move_number=current_move_number,
        grid=grid, 
        move_number=sd.Sudoku.move_number, 
        move_log=sd.Sudoku.move_log,
        sudoku_log=sd.Sudoku.sudoku_log,
        coordinates_log=sd.Sudoku.coordinates_log
    )

@views.route('/word_search', methods=['GET', 'POST'])
def word_search():
    grid = None
    found_words = []

    if request.method == 'GET':
        session.clear()

    added_words = session.get('added_words', [])

    if request.method == 'POST':
        move_action = request.form.get('move_action')
        if move_action == 'generate':
            if len(added_words) >= 5:
                word_search = WordSearch(10)
                for word in added_words:
                    word_search.add_word(word)
                grid = word_search.generate()
                session['word_search_info'] = {
                    'grid': grid,
                    'words': word_search.words,
                }
            else:
                flash('Add at least 5 words before generating the grid.', 'warning')
        elif move_action == 'solve':
            word_search_info = session.get('word_search_info')

            if word_search_info:
                word_search = WordSearch(10)
                word_search.grid = word_search_info['grid']
                word_search.words = word_search_info['words']

                grid = word_search.solve()
                found_words = word_search.words

        elif move_action == 'add_word':
            new_word = request.form.get('new_word')
            if new_word:
                new_word = new_word.upper()
                added_words.append(new_word)
                session['added_words'] = added_words

        elif move_action == 'reset':
            session.clear()
            added_words = []

    if grid is None:
        word_search = WordSearch(10)
        grid = word_search.generate()
        session['word_search_info'] = {
            'grid': grid,
            'words': word_search.words,
        }

    return render_template(
        "word_search.html",
        grid=grid,
        found_words=found_words,
        added_words=added_words
    )

@views.route('/play_sudoku', methods=['GET', 'POST'])
def play_sudoku():
    message = ""
    if request.method == 'POST':
        move_action = request.form.get('move_action')
        if move_action == 'play':
            row = int(request.form.get('row')) - 1
            column = int(request.form.get('column')) - 1
            number = int(request.form.get('number'))
            solved = True

            solved_grid = np.array(session['grid'])
            sd.Sudoku.solve(solved_grid)
            if 0 <= row < 9 and 0 <= column < 9 and 1 <= number <= 9 and session['grid'][row][column] == 0:
                session['grid'][row][column] = number

            user_grid = np.array(session['grid'])
            if solved_grid[row][column] == user_grid[row][column]:
                for i in range(9):
                    for j in range(9):
                        if user_grid[i][j] == 0:
                            solved = False
                            break
                if solved:
                    message = 'Čestitke, riješili ste sudoku!'
                else:
                    message = 'Tačan potez!'
                    session['grid'] = user_grid.tolist()
            else:
                session['grid'][row][column] = 0
                message = 'Pogrešan potez!'

            added_words = session.get('added_words', [])

        elif move_action == 'solve':
            solved_grid = np.array(session['grid'])
            sd.Sudoku.solve(solved_grid)
            session['grid'] = solved_grid.tolist()
            message = 'Rješenje je prikazano.'
        
        elif move_action == 'generate':
            difficulty = request.form.get('difficulty')
            if difficulty == 'easy':
                fill_probability = random.uniform(0.7, 0.9)
            elif difficulty == 'medium':
                fill_probability = random.uniform(0.4, 0.6)
            elif difficulty == 'hard':
                fill_probability = random.uniform(0.2, 0.4)
            grid = sd.Sudoku.sudoku_generator(fill_probability)
            session['grid'] = grid.tolist()
            message = 'Novi sudoku je generisan.'

    if request.method == 'GET':
        grid = np.zeros((9, 9), dtype=int)
        session['grid'] = grid.tolist()
    else:
        grid = session['grid']

    return render_template(
        "play_sudoku.html",
        grid=grid,
        message=message
    )

@views.route('/play_word_search', methods=['GET', 'POST'])
def play_word_search():
    message = ""
    words = []
    grid = [{'letter': ' ', 'found': False} for i in range(10) for j in range(10)]
    
    if request.method == 'GET':
        session['found_words'] = []

    if 'found_words' not in session:
        session['found_words'] = []
    found_words = session['found_words']

    if 'guesses' not in session:
        session['guesses'] = {}
    guessed_words_coordinates = session.get('guesses', {})

    file = open('words/words.txt', 'r')
    for line in file:
        words.append(line.strip())
    file.close()

    for i in range(len(words)):
        words[i] = words[i].upper()

    wordSearch = WordSearch(10)
    random.shuffle(words)

    for word in words:
        wordSearch.add_word(word)

    guessed_words_coordinates = session.get('guesses', {})

    if request.method == 'POST':
        grid = session['word_search_info']['grid']
        wordSearch.grid = grid
        move_action = request.form.get('move_action')
        session['guesses'] = guessed_words_coordinates

        if move_action == 'play_word_search':
            start_row = int(request.form.get('row_start'))
            start_column = int(request.form.get('column_start'))
            end_row = int(request.form.get('row_end'))
            end_column = int(request.form.get('column_end'))

            valid_directions = [
                (0, 1), (1, 0), (1, 1), (0, -1),
                (-1, 0), (-1, -1), (-1, 1), (1, -1)
            ]

            for direction in valid_directions:
                i, j = start_row - 1, start_column - 1
                guessed_word = ""
                coordinates = []

                while 0 <= i < 10 and 0 <= j < 10:
                    guessed_word += wordSearch.grid[i][j]
                    coordinates.append((i, j))
                    i += direction[0]
                    j += direction[1]

                    if guessed_word in words:
                        if (end_row - 1 == i - direction[0] and end_column - 1 == j - direction[1]) or (i < 0 or i >= 10 or j < 0 or j >= 10):
                            for k in range(len(guessed_word)):
                                i -= direction[0]
                                j -= direction[1]
                            message = f"Čestitke! Pronašli ste riječ '{guessed_word}'."
                            found_words.append(guessed_word)
                            grid = wordSearch.grid
                            guessed_words_coordinates[guessed_word] = coordinates  # Store coordinates for the guessed word
                            session['guesses'] = guessed_words_coordinates
                            break

            if not message:
                message = "Nažalost, riječ nije validna."

    elif request.method == 'GET':
        session.clear()
        grid = wordSearch.generate()

csp_enigmatic/website/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>CSP_Enigmatic</title>
    <link rel="stylesheet" type="text/css" href="static/styles.css">
    <link rel="stylesheet" type="text/css" href="static/sudoku.css">
    <link rel="stylesheet" type="text/css" href="static/crossword.css">
    <link rel="stylesheet" type="text/css" href="static/word_search.css">
    <link rel="stylesheet" type="text/css" href="static/play_sudoku.css">
</head>
<body>
    <header>
        <nav>
            <ul>
                <li><a id="home" class="menu-link" href="/">Početna strana</a></li>
                <li><a id="sudoku" class="menu-link" href="/sudoku">Sudoku</a></li>
                <!-- <li><a id="crossword" class="menu-link" href="/crossword">Ukrštenica</a></li> -->
                <li><a id="word_search" class="menu-link" href="/word_search">Osmosmjerka</a></li>
            </ul>
        </nav>
    </header>
    <div class="content">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

csp_enigmatic/website/templates/home.html
{% extends "base.html" %}

{% block content %}
<div class="content-container">
    <div class="sudoku-word-search-container home-container">
        <div class="sudoku-container">
            <p><a href="/play_sudoku">Igraj sudoku</a></p>

            <table class="sudoku outer-bold">
                {% for row in sudoku %}
                <tr>
                    {% for cell in row %}
                    <td class="sudoku-cell">
                        {% if cell != 0 %}
                            {{ cell }}
                        {% endif %}
                    </td>
                    {% endfor %}
                </tr>
                {% endfor %}
            </table>
        </div>
        <div class="word-search-container">
            <p><a href="/play_word_search">Igraj osmosmjerku</a></p>
            <table class="word_search">
                {% for row in word_search %}
                <tr>
                    {% for cell in row %}
                        {% if cell['found'] %}
                            <td class="word_search-cell highlighted-word">{{ cell['letter'] }}</td>
                        {% else %}
                            <td class="word_search-cell">{{ cell['letter'] if 'letter' in cell else cell }}</td>
                        {% endif %}
                    {% endfor %}
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>
{% endblock %}

csp_enigmatic/website/templates/play_sudoku.html
{% extends "base.html" %}

{% block content %}
<div class="content-container">
    <p><a href="/play_sudoku">Igraj sudoku</a></p>

    <div class="sudoku-container">
        <table class="sudoku">
            <thead>
                <tr>
                    <th class="sudoku-empty-cell"></th>
                    {% for col_number in range(1, 10) %}
                        <th class="sudoku-column-number">{{ col_number }}</th>
                        {% if col_number % 3 == 0 and col_number < 9 %}
                            <th class="vertical-line"></th>
                        {% endif %}
                    {% endfor %}
                </tr>
            </thead>
            <tbody>
                {% for row_number in range(1, 10) %}
                    <tr>
                        <th class="sudoku-row-number">{{ row_number }}</th>
                        {% for col_number in range(1, 10) %}
                            <td class="play_sudoku-cell">
                                {% if grid[row_number - 1][col_number - 1] != 0 %}
                                    {{ grid[row_number - 1][col_number - 1] }}
                                {% endif %}
                            </td>
                            {% if col_number % 3 == 0 and col_number < 9 %}
                                <td class="vertical-line"></td>
                            {% endif %}
                        {% endfor %}
                    </tr>
                    {% if row_number % 3 == 0 and row_number < 9 %}
                        <tr>
                            <td class="horizontal-line" colspan="19"></td>
                        </tr>
                    {% endif %}
                {% endfor %}
            </tbody>
        </table>        
    </div>
    <form method="POST" action="{{ url_for('views.play_sudoku') }}" class="sudoku-form">
        <label for="row">Red:</label>
        <input type="number" min="1" max="9" name="row" id="row" required>

        <label for="column">Kolona:</label>
        <input type="number" min="1" max="9" name="column" id="column" required>

        <label for="number">Broj:</label>
        <input type="number" min="1" max="9" name="number" id="number" required>

        <button type="submit" class="sudoku-button" name="move_action" value="play">Odigraj broj</button>
    </form>

    <form method="POST">
        <button type="submit" class="sudoku-button" name="move_action" value="solve">Riješi</button>
    </form>

    <form method="POST">
        <label for="difficulty">Težina:</label>
        <input type="radio" name="difficulty" value="easy" id="easy" required>
        <label for="easy">Lako</label>
        
        <input type="radio" name="difficulty" value="medium" id="medium">
        <label for="medium">Srednje</label>
        
        <input type="radio" name="difficulty" value="hard" id="hard">
        <label for="hard">Teško</label>
    
        <button type="submit" class="sudoku-button" name="move_action" value="generate">Generiši novi sudoku</button>
    </form>

    {% if message %}
    <p>{{ message }}</p>
    {% endif %}
</div>
{% endblock %}

csp_enigmatic/website/templates/play_word_search.html
{% extends "base.html" %}

{% block content %}
<div class="content-container">
    <p><a href="/play_word_search">Igraj osmosmjerku</a></p>
    <table class="word_search">
        <thead>
            <tr>
                <th></th> 
                {% for col_number in range(1, 11) %}
                    <th class="column-number">{{ col_number }}</th>
                {% endfor %}
            </tr>
        </thead>
        <tbody>
            {% for row_number in range(1, 11) %}
                <tr>
                    <th class="row-number">{{ row_number }}</th>
                    {% for cell in grid[row_number - 1] %}
                        {% if cell['found'] %}
                            {% set coordinates = (row_number - 1, loop.index0) %}
                            {% if coordinates in guessed_words_coordinates.values() %}
                                <td class="word_search-cell found-word">{{ cell['letter'] }}</td>
                            {% else %}
                                <td class="word_search-cell">{{ cell['letter'] }}</td>
                            {% endif %}
                        {% else %}
                            <td class="word_search-cell">{{ cell['letter'] if 'letter' in cell else cell }}</td>
                        {% endif %}
                    {% endfor %}
                </tr>
            {% endfor %}
        </tbody>        
        
    </table>

    <hr>

    <form method="POST" action="{{ url_for('views.play_word_search') }}" class="sudoku-form">
        <div class="row">
            <label for="row_start">Red početka riječi:</label>
            <input type="number" min="1" max="10" name="row_start" id="row_start" required>
        </div>
        <div class="row">
            <label for="column_start">Kolona početka riječi:</label>
            <input type="number" min="1" max="10" name="column_start" id="column_start" required>
        </div>
    
        <div class="row">
            <label for="row_end">Red kraja riječi:</label>
            <input type="number" min="1" max="10" name="row_end" id="row_end" required>
        </div>
        <div class="row">
            <label for="column_end">Kolona kraja riječi:</label>
            <input type="number" min="1" max="10" name="column_end" id="column_end" required>
        </div>
        <button type="submit" class="sudoku-button" name="move_action" value="play_word_search">Odigraj</button>
    </form>    
    <form method="POST">
        <button type="submit" name="move_action" value="generate">Generiši novu osmosmjerku</button>
        <button type="submit" name="move_action" value="solve">Riješi</button>
    </form>
    {% if message %}
    <p>{{ message }}</p>
    {% endif %}
    <h3>Pronađene riječi:</h3>
    <ul>
        {% for word in found_words %}
            <li>{{ word }}</li>
        {% endfor %}
    </ul>
    <hr>
    <h3>Moguće riječi:</h3>
    <ul>
        {% for word in added_words %}
            <li>{{ word }}</li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

csp_enigmatic/website/templates/sudoku.html
{% extends "base.html" %}
{% block content %}
<div class="content-container">
    <p><a href="/play_sudoku">Igraj sudoku</a></p>

    <table class="sudoku outer-bold">
        {% for row_index in range(sudoku_log[current_move_number]|length) %}
        <tr>
            {% for col_index in range(sudoku_log[current_move_number][row_index]|length) %}
            {% set cell = sudoku_log[current_move_number][row_index][col_index] %}
            {% set cell_coordinates = [row_index, col_index] %}
            <td class="sudoku-cell{% if cell_coordinates in coordinates_log[current_move_number] %} highlighted{% endif %}">
                {% if cell != 0 %}
                    {{ cell }}
                {% endif %}
            </td>
            {% endfor %}
        </tr>
        {% endfor %}
    </table>
    <form method="post">
        <button type="submit" name="move_action" value="previous">Prethodno stanje</button>
        <button type="submit" name="move_action" value="next">Naredno stanje</button>
        <button type="submit" name="move_action" value="solve">Riješi</button>
        <button type="submit" name="move_action" value="reset">Resetuj</button>
        <button type="submit" name="move_action" value="generate">Novi sudoku</button>
    </form>
    <hr>
    <p>Stanje: {{ current_move_number }}/{{ move_number }}</p>
    <hr>
    {% if move_log %}
    <h3>Zapisnik:</h3>
    <ul>
        {% for move in move_log[current_move_number] %}
        <li>{{ move }}</li>
        {% endfor %}
    </ul>
    {% endif %}
</div>
{% endblock %}

csp_enigmatic/website/templates/word_search.html
{% extends "base.html" %}
{% block content %}
<div class="content-container">
    <p><a href="/play_word_search">Igraj osmosmjerku</a></p>
    <table class="word_search">
        {% for row in grid %}
        <tr>
            {% for cell in row %}
                {% if cell['found'] %}
                    <td class="word_search-cell highlighted-word">{{ cell['letter'] }}</td>
                {% else %}
                    <td class="word_search-cell">{{ cell['letter'] if 'letter' in cell else cell }}</td>
                {% endif %}
            {% endfor %}
        </tr>
        {% endfor %}
    </table>
    <form method="POST">
        <button type="submit" name="move_action" value="generate" {% if not grid or added_words|length < 5 or added_words|length > 10 %}disabled{% endif %}>Generiši</button>
        <button type="submit" name="move_action" value="solve">Riješi</button>
        <input type="text" name="new_word" placeholder="Unesite riječ" {% if added_words|length > 10 %}disabled{% endif %}>
        <button type="submit" name="move_action" value="add_word" {% if added_words|length > 10 %}disabled{% endif %}>Dodaj riječ</button>
        <button type="submit" name="move_action" value="reset">Resetuj</button>
    </form>
    <div class="word-list">
        {% if added_words|length < 5 %}
        <p class="warning-message">Dodajte barem 5 riječi da biste generisali osmosmjerku.</p>
        {% elif added_words|length > 10 %}
        <p class="warning-message">Dosegli ste limit od 10 riječi.</p>
        {% endif %}
        <h3>Dodate riječi:</h3>
        <ul>
            {% for word in added_words %}
                <li>{{ word }}</li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}